version: '3.4'

services:
  server:
    image: gilgates-api-server
    build:
      context: .
      dockerfile: ./Dockerfile.server
    ports:
      - 8000:8000
    env_file:
      - .env

  worker:
    image: gilgates-api-worker
    build:
      context: .
      dockerfile: ./Dockerfile.worker
    env_file:
      - .env

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
