version: '3.4'

services:
  server:
    image: gilgates-api-server
    build:
      context: .
      dockerfile: ./Dockerfile.server
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - worker

  worker:
    image: gilgates-api-worker
    build:
      context: .
      dockerfile: ./Dockerfile.worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
